name: 'mawl: Make a Weblog!'
description: 'mawl: Make a Weblog! mawl converts repos w/markdown files into full blog-like static sites for hosting on GH Pages.'
author: "Phill MV"
branding:
  icon: 'book-open'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  CNAME:
    description: 'Your GitHub Pages CNAME, if any.'
    required: false
    default: ''
  INPUT_FOLDER:
    description: 'A subdirectory of the input repository which contains the markdown we wish to convert to a static site, i.e. docs/ or src/blog'
    required: false
    default: ''
  GITHUB_REPOSITORY:
    description: 'Target GitHub repository, which receives the built static site.'
    required: false
    default: ${{ github.repository }}
  REMOTE_BRANCH:
    description: 'Target repository branch for the built static site.'
    required: false
    default: 'gh-pages'
  GITHUB_ACTOR:
    description: 'Name of the deploy actor'
    required: false
    default: ${{ github.actor }}
  GITHUB_TOKEN:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: false
    default: ${{ github.token }}
